name: Increment chooyijie_refresh

on:
  workflow_dispatch:

jobs:
  increment-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read current refresh value
        id: get-refresh
        run: |
          REFRESH=$(grep -oP 'chooyijie_refresh=\K\d+' README.md | head -1)
          echo "refresh=$REFRESH" >> $GITHUB_OUTPUT

      - name: Increment and update README
        id: update-readme
        run: |
          OLD=${{ steps.get-refresh.outputs.refresh }}
          NEW=$(( OLD + 1 ))
          sed -i "s/chooyijie_refresh=$OLD/chooyijie_refresh=$NEW/g" README.md
          echo "new_refresh=$NEW" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Increment chooyijie_refresh to ${{ steps.update-readme.outputs.new_refresh }}"
          git push
