name: Increment chooyijie_refresh

on:
  workflow_dispatch:

jobs:
  increment-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read current refresh value
        id: get-refresh
        run: |
          REFRESH=$(grep -oP 'chooyijie_refresh=\K\d+' README.md | head -1)
          echo "Current value: $REFRESH"
          echo "refresh=$REFRESH" >> $GITHUB_OUTPUT

      - name: Increment refresh value
        run: |
          NEW_REFRESH=$(( ${{ steps.get-refresh.outputs.refresh }} + 1 ))
          sed -i "s/chooyijie_refresh=${{ steps.get-refresh.outputs.refresh }}/chooyijie_refresh=$NEW_REFRESH/g" README.md
          echo "New value: $NEW_REFRESH"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Increment chooyijie_refresh to $NEW_REFRESH"
          git push
